# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-dirigible-cf"
    version = "6.3.30"

[stack]
id = "org.eclipse.dirigible"
build-image = "dirigiblelabs/buildpacks-stack-build-dirigible-cf:6.3.30"
run-image = "dirigiblelabs/buildpacks-stack-run-dirigible-cf:6.3.30"
