# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-dirigible-kyma"
    version = "6.3.30"

[stack]
id = "org.eclipse.dirigible"
build-image = "dirigiblelabs/buildpacks-stack-build-dirigible-kyma:6.3.30"
run-image = "dirigiblelabs/buildpacks-stack-run-dirigible-kyma:6.3.30"
