name: Build

on:
  push:
    branches: 
      - main
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Cache local Maven repository
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-
    - name: Set up JDK 13
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '13'
        architecture: x64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        install: true
    - name: Set Multi-Builder Docker Buildx
      run: docker buildx create --use --name multi-builder --platform linux/arm64,linux/amd64,linux/arm64/v8
    - name: Maven Build
      run: mvn clean install -Dmaven.javadoc.skip=false
    - name: Docker Login
      run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
    - name: Push Dirigible (Spring)
      run: |
        cd components/app-all
        docker build --load -t dirigible .
        docker tag dirigible dirigiblelabs/dirigible
        docker push dirigiblelabs/dirigible
        docker image prune -a -f
        cd ../../
    - name: Push Dirigible
      run: |
        cd releng/server-all
        docker build --load -t dirigible-base-platform -f Dockerfile-base .
        docker tag dirigible-base-platform dirigiblelabs/dirigible-base-platform
        docker push dirigiblelabs/dirigible-base-platform
        docker build --load -t dirigible-all .
        docker tag dirigible-all dirigiblelabs/dirigible-all
        docker push dirigiblelabs/dirigible-all
        docker image prune -a -f
        cd ../../
    - name: Push Dirigible - Keycloak
      run: |
        cd releng/server-keycloak-all
        docker build --load -t dirigible-base-platform-keycloak -f Dockerfile-base .
        docker tag dirigible-base-platform-keycloak dirigiblelabs/dirigible-base-platform-keycloak
        docker push dirigiblelabs/dirigible-base-platform-keycloak
        docker build --load -t dirigible-keycloak .
        docker tag dirigible-keycloak dirigiblelabs/dirigible-keycloak
        docker push dirigiblelabs/dirigible-keycloak
        docker image prune -a -f
        cd ../../
    - name: Push Dirigible - Keycloak - Runtime
      run: |
        cd releng/server-runtime-keycloak
        docker build --load -t dirigible-base-platform-runtime-keycloak -f Dockerfile-base .
        docker tag dirigible-base-platform-runtime-keycloak dirigiblelabs/dirigible-base-platform-runtime-keycloak
        docker push dirigiblelabs/dirigible-base-platform-runtime-keycloak
        docker build --load -t dirigible-runtime-keycloak .
        docker tag dirigible-runtime-keycloak dirigiblelabs/dirigible-runtime-keycloak
        docker push dirigiblelabs/dirigible-runtime-keycloak
        docker image prune -a -f
        cd ../../

